# Generated by Django 6.0.5 on 2026-05-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('layout_type', models.CharField(choices=[('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait')], default='LANDSCAPE', max_length=50)),
                ('resoluttion_width', models.IntegerField(default=1920)),
                ('resoluttion_height', models.IntegerField(default=1080)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('layout_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_layouts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayoutZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('TEXT', 'Text'), ('QUEUE', 'Queue'), ('DOCTOR', 'Doctor'), ('EMERGENCY', 'Emergency'), ('CLOCK', 'Clock'), ('WEATHER', 'Weather'), ('NEWS', 'News')], default='VIDEO', max_length=50)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('z_index', models.IntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='layouts.layout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
