# Generated by Django 6.0.5 on 2026-05-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_layout_organization_and_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='layout_config',
        ),
        migrations.RemoveField(
            model_name='layoutzone',
            name='config',
        ),
    ]
