# Generated by Django 6.0.5 on 2026-05-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_remove_layout_layout_config_remove_layoutzone_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutZone',
        ),
    ]
