# Generated by Django 6.0.5 on 2026-05-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_status_devicehealth'),
        ('facilities', '0011_alter_facility_facility_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_device', to='facilities.block'),
        ),
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_device', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='device',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_device', to='facilities.floor'),
        ),
    ]
