# Generated by Django 6.0.5 on 2026-05-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_block_device_facility_alter_device_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehealth',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='devices.device'),
        ),
    ]
