# Generated by Django 6.0.5 on 2026-05-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_devicehealth_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehealth',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='ONLINE', max_length=20),
        ),
    ]
