# Generated by Django 6.0.5 on 2026-06-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicehealth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehealth',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
