# Generated by Django 6.0.5 on 2026-05-11 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_remove_device_status_devicehealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('INTERRUPTED', 'Interrupted')], default='SCHEDULED', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='devices.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
