# Generated by Django 6.0.5 on 2026-05-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcasting', '0001_initial'),
        ('layouts', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='schedules.doctorschedule'),
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='layouts.layout'),
        ),
        migrations.AddField(
            model_name='broadcastsession',
            name='opdschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_sessions', to='schedules.opdschedule'),
        ),
    ]
