# Generated by Django 6.0.5 on 2026-05-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0003_broadcastsession_organization'),
        ('devices', '0004_alter_devicehealth_device'),
        ('facilities', '0011_alter_facility_facility_admin_and_more'),
        ('layouts', '0002_layout_organization_and_constraints'),
        ('organizations', '0003_alter_organizationsubscription_status'),
        ('schedules', '0005_doctor_facility_doctor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_facility', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_device', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='doctor_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_doctor', to='schedules.doctorschedule'),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_layout', to='layouts.layout'),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='opdschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_opd', to='schedules.opdschedule'),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_organizations', to='organizations.organization'),
        ),
    ]
