# Generated by Django 6.0.5 on 2026-05-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0004_broadcastsession_facility_and_more'),
        ('layouts', '0004_delete_layoutzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastsession',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_layout', to='layouts.layout'),
        ),
    ]
