# Generated by Django 6.0.5 on 2026-05-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0005_alter_broadcastsession_layout'),
        ('schedules', '0006_add_opdroom_block_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastsession',
            name='doctor_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_doctor', to='schedules.doctorschedule'),
        ),
        migrations.AlterField(
            model_name='broadcastsession',
            name='opdschedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_opd', to='schedules.opdschedule'),
        ),
    ]
