# Generated by Django 6.0.5 on 2026-05-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0006_alter_broadcastsession_doctor_schedule_and_more'),
        ('media_library', '0003_mediaasset_facility_and_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastsession',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_media', to='media_library.mediaasset'),
        ),
    ]
