# Generated by Django 6.0.5 on 2026-05-09 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('HTML', 'HTML')], default='VIDEO', max_length=20)),
                ('file', models.FileField(upload_to='media_assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_thumbnails/')),
                ('duration', models.DurationField(blank=True, help_text='Duration of the media asset (applicable for videos and audio files)', null=True)),
                ('tags', models.JSONField(blank=True, help_text='List of tags associated with the media asset', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
