# Generated by Django 6.0.5 on 2026-05-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
        ('facilities', '0011_alter_facility_facility_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='facilities.facility'),
        ),
    ]
