# Generated by Django 6.0.5 on 2026-07-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationsubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin')], default='SUPER_ADMIN', max_length=20),
        ),
    ]
