# Generated by Django 6.0.5 on 2026-05-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_mediaasset_facility_and_related_names'),
        ('playlists', '0003_playlist_facility'),
        ('schedules', '0006_add_opdroom_block_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='doctor_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_playlist_items', to='schedules.doctorschedule'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='opd_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_playlist_items', to='schedules.opdschedule'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_playlist_items', to='media_library.mediaasset'),
        ),
    ]
