# Generated by Django 6.0.5 on 2026-05-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0011_alter_facility_facility_admin_and_more"),
        ("organizations", "0003_alter_organizationsubscription_status"),
        ("schedules", "0005_doctor_facility_doctor_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="opdroom",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opd_rooms",
                to="facilities.block",
            ),
        ),
        migrations.AddField(
            model_name="opdroom",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opd_rooms",
                to="facilities.floor",
            ),
        ),
    ]
