# Generated by Django 6.0.5 on 2026-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_add_opdroom_block_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='out_of_station_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='out_of_station_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
