# Generated by Django 6.0.5 on 2026-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_doctorschedule_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='out_of_station_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='out_of_station_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
