# Generated by Django 6.0.5 on 2026-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_rename_out_of_station_end_date_doctorschedule_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdschedule',
            name='opd_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
