# Generated by Django 6.0.5 on 2026-05-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_opdschedule_opd_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdschedule',
            name='opd_date',
        ),
    ]
