# Generated by Django 6.0.5 on 2026-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_remove_opdschedule_opd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdschedule',
            name='opd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opdschedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
