# Generated by Django 6.0.5 on 2026-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
