# Generated by Django 6.0.5 on 2026-05-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_block_facility_blocks_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Floor',
        ),
    ]
