# Generated by Django 6.0.5 on 2026-05-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_rename_location_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['name'], 'verbose_name': 'Floor', 'verbose_name_plural': 'Floors'},
        ),
    ]
