# Generated by Django 6.0.5 on 2026-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_floor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
