# Generated by Django 6.0.5 on 2026-05-14 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facility_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_facility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'STAFF', 'role'}, null=True, related_name='staff_facility', to=settings.AUTH_USER_MODEL),
        ),
    ]
