# Generated by Django 6.0.5 on 2026-05-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_facility_facility_admin_facility_facility_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='blocks',
            field=models.ManyToManyField(blank=True, null=True, related_name='facilities', to='facilities.block'),
        ),
    ]
