# Generated by Django 6.0.5 on 2026-05-14 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_alter_facility_blocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='blocks',
        ),
        migrations.AddField(
            model_name='block',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'ADMIN', 'role'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_facility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='unique_block_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('block', 'name'), name='unique_floor_per_block'),
        ),
    ]
