# Generated by Django 6.0.5 on 2026-05-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_alter_facility_facility_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_facility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STAFF'}, related_name='staff_facility', to=settings.AUTH_USER_MODEL),
        ),
    ]
