# Generated by Django 6.0.5 on 2026-05-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_alter_facility_facility_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
