# Generated by Django 6.0.5 on 2026-05-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneotp'),
        ('schedules', '0002_rename_specialization_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
